### ISSUE TITLE
Remove unnecessary requirements from setup

### ISSUE THREAD

**Issue by davejm** [mehdidc/ramp-leaderboard#1]
Please remove clize and sigtools from setup.py requires

**Comment by mehdidc** [comment]
Thanks for noticing this, I will remove them. Note that there is a PR (https://github.com/paris-saclay-cds/ramp-workflow/pull/136) that will integrate ramp_loaderboard into ramp-workflow (https://github.com/paris-saclay-cds/ramp-workflow), so this repo will probably be removed when it will be merged.

**Comment by davejm** [comment]
Thanks! Yes, I've seen it but didn't want to use the fork of the workflow library. Looking forward to this being merged into that package though! Thanks
